name: 'Setup Evo.lua environment'
description: 'Setup an Evo.lua environment by downloading a specific runtime version and adding it to the PATH.'
author: 'Evo.lua authors'
branding:
  icon: code
  color: green

inputs:
  version:
    description: 'Version tag of the release to download.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        PLATFORM=$(uname)
        if [ "$PLATFORM" = "Linux" ]; then
          echo "Installing dependencies for Linux"
          sudo apt-get update
          sudo apt-get install --yes libgtk-3-0 libwebkit2gtk-4.0-37
        fi

    - name: Download tagged release
      shell: bash
      run: |
        set -e
        GITHUB_ORGANIZATION="evo-lua"
        GITHUB_REPOSITORY="evo-runtime"
        REQUIRED_RUNTIME_VERSION=$1

        PLATFORM=$(uname)

        echo "Downloading release for version $REQUIRED_RUNTIME_VERSION"

        ASSET_FILE_NAME=""
        EXECUTABLE_NAME=""
        GITHUB_BASE_URL="https://github.com/$GITHUB_ORGANIZATION/$GITHUB_REPOSITORY/releases/download"

        echo "Detected platform: $PLATFORM"

        case $PLATFORM in
          MINGW64_NT*|CYGWIN_NT*|MSYS_NT*)
            ASSET_FILE_NAME="evo.exe"
            EXECUTABLE_NAME="evo.exe"
            ;;
          Linux)
            ASSET_FILE_NAME="evo-linux-x64"
            EXECUTABLE_NAME="evo"
            ;;
          Darwin)
            ASSET_FILE_NAME="evo-macos-x64"
            EXECUTABLE_NAME="evo"
            ;;
          *)
            echo "Unsupported platform: $PLATFORM"
            exit 1
            ;;
        esac

        DOWNLOAD_LINK="$GITHUB_BASE_URL/$REQUIRED_RUNTIME_VERSION/$ASSET_FILE_NAME"
        echo "Fetching GitHub release: $DOWNLOAD_LINK"
        curl --location --silent --output "$EXECUTABLE_NAME" "$DOWNLOAD_LINK"
        chmod +x $EXECUTABLE_NAME

        echo "Downloaded $ASSET_FILE_NAME for platform: $PLATFORM"
        echo "Saved here: $(pwd)/$EXECUTABLE_NAME"

    - name: Add executable to PATH
      run: echo "$(pwd)" >> $GITHUB_PATH
      shell: bash
